"""empty message

Revision ID: 4c68d7df974e
Revises: 772ad80d6545
Create Date: 2022-11-06 23:12:48.899263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c68d7df974e'
down_revision = '772ad80d6545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_user_id_key', 'chat', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('chat_user_id_key', 'chat', ['user_id'])
    # ### end Alembic commands ###
