"""empty message

Revision ID: 68711e6bbafb
Revises: 5dfe81960708
Create Date: 2022-10-19 15:27:04.770658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68711e6bbafb'
down_revision = '5dfe81960708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('baths', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('join_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'join_date')
    op.drop_column('properties', 'baths')
    # ### end Alembic commands ###
