"""empty message

Revision ID: 772ad80d6545
Revises: 77bd01c5744d
Create Date: 2022-11-06 15:18:51.393520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772ad80d6545'
down_revision = '77bd01c5744d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=150), nullable=True),
    sa.Column('join_time', sa.Time(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_chat_join_time'), 'chat', ['join_time'], unique=False)
    op.create_index(op.f('ix_chat_message'), 'chat', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message'), table_name='chat')
    op.drop_index(op.f('ix_chat_join_time'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
