"""empty message

Revision ID: d3cd7b57b216
Revises: fffe55886409
Create Date: 2022-10-25 11:36:57.531285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cd7b57b216'
down_revision = 'fffe55886409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_join_date'), 'properties', ['join_date'], unique=False)
    op.create_index(op.f('ix_properties_join_time'), 'properties', ['join_time'], unique=False)
    op.add_column('users', sa.Column('joined_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_users_joined_at'), 'users', ['joined_at'], unique=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_joined_at'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'joined_at')
    op.drop_index(op.f('ix_properties_join_time'), table_name='properties')
    op.drop_index(op.f('ix_properties_join_date'), table_name='properties')
    # ### end Alembic commands ###
